<?php

namespace AppBundle\Repository;

/**
 * EtaCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtaCmdRepository extends \Doctrine\ORM\EntityRepository
{
}
