<?php

namespace AppBundle\Repository;

/**
 * lineCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lineCmdRepository extends \Doctrine\ORM\EntityRepository
{
}
