<?php

namespace AppBundle\Repository;

/**
 * ModePayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePayRepository extends \Doctrine\ORM\EntityRepository
{
}
