<?php

namespace AppBundle\Repository;

/**
 * RefModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
