app_etacmd:
    resource: "@AppBundle/Resources/config/routing/etacmd.yml"
    prefix:   /etacmd



app_region:
    resource: "@AppBundle/Resources/config/routing/region.yml"
    prefix:   /region
app_ville:
    resource: "@AppBundle/Resources/config/routing/ville.yml"
    prefix:   /ville
app_modepay:
    resource: "@AppBundle/Resources/config/routing/modepay.yml"
    prefix:   /modepay
app_marque:
    resource: "@AppBundle/Resources/config/routing/marque.yml"
    prefix:   /marque
app_modele:
    resource: "@AppBundle/Resources/config/routing/modele.yml"
    prefix:   /modele
app_refmodele:
    resource: "@AppBundle/Resources/config/routing/refmodele.yml"
    prefix:   /refmodele
app_produit:
    resource: "@AppBundle/Resources/config/routing/produit.yml"
    prefix:   /produit
app_depot:
    resource: "@AppBundle/Resources/config/routing/depot.yml"
    prefix:   /depot